/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.attendance_manager;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.jar.Attributes.Name;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import login.Login;
import database.databaseConnection;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author amola
 */
public class Teacher extends javax.swing.JFrame {
    Connection conn,conn1;
    ResultSet rs;
    PreparedStatement pat;
    Statement st;
    
    String teacher_id;
    String username;
    String password;
    /**
     * Creates new form Teacher_temp
     */
    public Teacher() {
        initComponents();
        compo();
        setMenuClicked();

        //getTID();
    }
    
    public Teacher(String username,String password) {
        initComponents();
        compo();
        setMenuClicked();
        this.username=username;
        this.password=password;
        try{
        fillClassCode();
        fillSubjectId();
        }catch(Exception e)
        {
            
        }
        
    }
    public void compo()
    {
        tdashboardpanel.setVisible(false);
        addattpanel.setVisible(true);
        addatt2panel.setVisible(true);
        displayattpanel.setVisible(false);
        logoutpanel.setVisible(false);
    }
    
    public void setMenuClicked(){
        addattbutton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 6, 0, 0, new java.awt.Color(255, 255, 255)));
        brbutton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(255, 255, 255)));
    }
    
   public void fillClassCode() throws SQLException 
   {
            
           Connection conn = databaseConnection.connection();
            Statement st = conn.createStatement();
 
  ResultSet rr1=st.executeQuery("select class_code from subject_assign where teacher_id="+username);
            class_input.removeAllItems();
 while (rr1.next()) 
     {  
     String ccd = rr1.getString("class_code");
     class_input.addItem(ccd);
     }
 
   }
   
//   public void getTID() throws SQLException 
//   {
//            
//           Connection conn = databaseConnection.connection();
//            Statement st = conn.createStatement();
// 
//  teacher_id=("select teacher_id  from subject_assign where teacher_id="+teacher_id);
//
//   }
    
    
   public void fillSubjectId() throws SQLException 
   {
            
           Connection conn = databaseConnection.connection();
            Statement st = conn.createStatement();
 
  ResultSet rr1=st.executeQuery("select subject_id from subject_assign where teacher_id="+username);
            subject_input.removeAllItems();
 while (rr1.next()) 
    {  

     String ccd = rr1.getString("subject_id");
     subject_input.addItem(ccd);
    }
   }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LogOut = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        addattbutton = new rojeru_san.RSButton();
        brbutton = new rojeru_san.RSButton();
        tdbbutton = new rojeru_san.RSButton();
        addattpanel = new javax.swing.JPanel();
        addattlabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        addatt2panel = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        time_input = new javax.swing.JComboBox<>();
        class_input = new javax.swing.JComboBox<>();
        subject_input = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        date_input = new com.toedter.calendar.JDateChooser();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        display_table = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        select_input1 = new javax.swing.JButton();
        displayattpanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        attendance_table = new javax.swing.JTable();
        addattlabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        logs_table = new javax.swing.JTable();
        logoutpanel = new javax.swing.JPanel();
        logout = new javax.swing.JPanel();
        addsubject1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        logout_no_button = new javax.swing.JButton();
        logout_yes_button = new javax.swing.JButton();
        tdashboardpanel = new javax.swing.JPanel();
        jSeparator9 = new javax.swing.JSeparator();
        ttSubs = new javax.swing.JLabel();
        tNoOfSub = new javax.swing.JLabel();
        dashboardlabel = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tdbdets = new rojerusan.RSTableMetro();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        tNoOfclasses = new javax.swing.JLabel();
        ttClasses = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        ttSubs1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1255, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(31, 148, 251));
        header.setForeground(new java.awt.Color(255, 255, 255));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(240, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(16, 16, 16));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, -1, 30));

        LogOut.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        LogOut.setForeground(new java.awt.Color(16, 16, 16));
        LogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogOut.setText("Logout");
        LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutMouseClicked(evt);
            }
        });
        header.add(LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 0, 80, 30));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(16, 16, 16));
        jLabel34.setText(" Attendance Manager");
        header.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 170, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(16, 16, 16));
        jLabel8.setText("•  Teacher");
        header.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 100, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(16, 16, 16));
        jLabel9.setText("MarkitUp -");
        header.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 90, 30));

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 30));

        jPanel1.setBackground(new java.awt.Color(31, 46, 85));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addattbutton.setBackground(new java.awt.Color(31, 46, 85));
        addattbutton.setText("ADD ATTENDANCE");
        addattbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addattbuttonMouseClicked(evt);
            }
        });
        addattbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addattbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(addattbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 50));

        brbutton.setBackground(new java.awt.Color(31, 46, 85));
        brbutton.setText("DISPLAY RECORDS");
        brbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(brbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, 50));

        tdbbutton.setBackground(new java.awt.Color(31, 46, 85));
        tdbbutton.setText("DASHBOARD");
        tdbbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdbbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(tdbbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 200, 690));

        addattpanel.setBackground(new java.awt.Color(255, 255, 255));
        addattpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addattlabel.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        addattlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addattlabel.setText("Add Attendance");
        addattlabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        addattlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addattlabelMouseClicked(evt);
            }
        });
        addattpanel.add(addattlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, 40));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        addattpanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1050, 30));

        addatt2panel.setBackground(new java.awt.Color(255, 255, 255));
        addatt2panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Class");
        addatt2panel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 40));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Subject");
        addatt2panel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, 40));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Date");
        addatt2panel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, -1, 40));

        time_input.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        time_input.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09:10 - 10:10", "10:10 - 11:10", "11:20 - 12:20", "12:20 - 01:20", "02:00 - 03:00", "03:00 - 04:00", "04:00 - 05:00", "05:00 - 06:00" }));
        time_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time_inputActionPerformed(evt);
            }
        });
        addatt2panel.add(time_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 110, 40));

        class_input.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        class_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                class_inputActionPerformed(evt);
            }
        });
        addatt2panel.add(class_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 130, 40));

        subject_input.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subject_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject_inputActionPerformed(evt);
            }
        });
        addatt2panel.add(subject_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 180, 40));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Timing");
        addatt2panel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, 40));
        addatt2panel.add(date_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 140, 40));

        jButton6.setBackground(new java.awt.Color(31, 46, 85));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Submit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        addatt2panel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 500, 100, 40));

        display_table.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        display_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Roll_no", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        display_table.setRowHeight(27);
        display_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                display_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(display_table);

        addatt2panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 830, 410));

        jButton7.setBackground(new java.awt.Color(31, 46, 85));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Done");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        addatt2panel.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, 90, 40));

        select_input1.setBackground(new java.awt.Color(31, 46, 85));
        select_input1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        select_input1.setForeground(new java.awt.Color(255, 255, 255));
        select_input1.setText("Select all");
        select_input1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_input1ActionPerformed(evt);
            }
        });
        addatt2panel.add(select_input1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 440, 100, 40));

        addattpanel.add(addatt2panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 1030, 570));

        getContentPane().add(addattpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 1070, 690));

        displayattpanel.setBackground(new java.awt.Color(255, 255, 255));
        displayattpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        attendance_table.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        attendance_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Roll_no", "Student_name", "Attendance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        attendance_table.setName(""); // NOI18N
        attendance_table.setRowHeight(25);
        jScrollPane1.setViewportView(attendance_table);
        if (attendance_table.getColumnModel().getColumnCount() > 0) {
            attendance_table.getColumnModel().getColumn(0).setResizable(false);
            attendance_table.getColumnModel().getColumn(1).setResizable(false);
            attendance_table.getColumnModel().getColumn(2).setResizable(false);
        }

        displayattpanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 560, 520));

        addattlabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        addattlabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addattlabel1.setText("Records");
        addattlabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addattlabel1MouseClicked(evt);
            }
        });
        displayattpanel.add(addattlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, 40));

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        displayattpanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1050, 30));

        logs_table.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        logs_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Class_code", "Subject_code", "Date", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        logs_table.setRowHeight(25);
        logs_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logs_tableMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logs_tableMouseExited(evt);
            }
        });
        logs_table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                logs_tableKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(logs_table);
        if (logs_table.getColumnModel().getColumnCount() > 0) {
            logs_table.getColumnModel().getColumn(0).setResizable(false);
            logs_table.getColumnModel().getColumn(1).setResizable(false);
            logs_table.getColumnModel().getColumn(2).setResizable(false);
            logs_table.getColumnModel().getColumn(3).setHeaderValue("Time");
        }

        displayattpanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 430, 520));

        getContentPane().add(displayattpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 1070, 690));

        logoutpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setBackground(new java.awt.Color(255, 255, 255));
        logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addsubject1.setBackground(new java.awt.Color(16, 16, 16));
        addsubject1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 153, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setBackground(new java.awt.Color(31, 46, 85));
        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(31, 46, 85));
        jLabel46.setText("Do you really want to Logout ?");
        jPanel2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 70, 310, 30));

        logout_no_button.setBackground(new java.awt.Color(31, 46, 85));
        logout_no_button.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        logout_no_button.setForeground(new java.awt.Color(255, 255, 255));
        logout_no_button.setText("No");
        logout_no_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_no_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(logout_no_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 130, 50));

        logout_yes_button.setBackground(new java.awt.Color(31, 46, 85));
        logout_yes_button.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        logout_yes_button.setForeground(new java.awt.Color(255, 255, 255));
        logout_yes_button.setText("Yes");
        logout_yes_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_yes_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(logout_yes_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 130, 50));

        addsubject1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 470, 260));

        logout.add(addsubject1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 1260, 720));

        logoutpanel.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, -1, 1260, 720));

        getContentPane().add(logoutpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 720));

        tdashboardpanel.setBackground(new java.awt.Color(255, 255, 255));
        tdashboardpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator9.setBackground(new java.awt.Color(153, 153, 153));
        tdashboardpanel.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1050, 30));

        ttSubs.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ttSubs.setText("Assigned Subjects:");
        tdashboardpanel.add(ttSubs, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        tNoOfSub.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tNoOfSub.setForeground(new java.awt.Color(255, 255, 255));
        tNoOfSub.setText("00");
        tdashboardpanel.add(tNoOfSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        dashboardlabel.setBackground(new java.awt.Color(255, 255, 255));
        dashboardlabel.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        dashboardlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboardlabel.setText("Dashboard");
        dashboardlabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        dashboardlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardlabelMouseClicked(evt);
            }
        });
        tdashboardpanel.add(dashboardlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, 40));

        tdbdets.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        tdbdets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tdbdets.setColorBackgoundHead(new java.awt.Color(31, 46, 85));
        tdbdets.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tdbdets.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tdbdets.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tdbdets.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tdbdets.setFuenteFilas(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tdbdets.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tdbdets.setRowHeight(30);
        tdbdets.setShowGrid(false);
        jScrollPane9.setViewportView(tdbdets);

        tdashboardpanel.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 1010, 260));

        jPanel5.setBackground(new java.awt.Color(31, 46, 85));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(31, 148, 251));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tNoOfclasses.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tNoOfclasses.setForeground(new java.awt.Color(255, 255, 255));
        tNoOfclasses.setText("00");
        jPanel6.add(tNoOfclasses, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 90));

        ttClasses.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ttClasses.setForeground(new java.awt.Color(255, 255, 255));
        ttClasses.setText("Total Classes");
        jPanel5.add(ttClasses, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        tdashboardpanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 240, 140));

        jPanel3.setBackground(new java.awt.Color(31, 46, 85));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(31, 148, 251));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 90));

        ttSubs1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ttSubs1.setForeground(new java.awt.Color(255, 255, 255));
        ttSubs1.setText("Total Subjects");
        jPanel3.add(ttSubs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        tdashboardpanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 240, 140));

        getContentPane().add(tdashboardpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 1070, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseClicked
        // TODO add your handling code here:
        tdashboardpanel.setVisible(false);
        addattpanel.setVisible(false);
        addatt2panel.setVisible(false);
        displayattpanel.setVisible(false);
        jPanel1.setVisible(false);
        logoutpanel.setVisible(true);
    }//GEN-LAST:event_LogOutMouseClicked

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        addattpanel.setVisible(false);

    }//GEN-LAST:event_profileActionPerformed

    private void drButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drButton3ActionPerformed
        // TODO add your handling code here:
        addattpanel.setVisible(false);
    }//GEN-LAST:event_drButton3ActionPerformed

    private void addattlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addattlabelMouseClicked
        // TODO add your handling code here:

        addattlabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        LogOut.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        addatt2panel.setVisible(true);
    }//GEN-LAST:event_addattlabelMouseClicked

    private void time_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_time_inputActionPerformed

    private void class_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_class_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_class_inputActionPerformed

    private void subject_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject_inputActionPerformed

    private void addattbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addattbuttonMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_addattbuttonMouseClicked

    private void addattbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addattbuttonActionPerformed
        // TODO add your handling code here:
        tdbbutton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(255, 255, 255)));
        addattbutton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 6, 0, 0, new java.awt.Color(255, 255, 255)));
        brbutton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(255, 255, 255)));
    

        try{
        tdashboardpanel.setVisible(false);
        addattpanel.setVisible(true);
        addatt2panel.setVisible(true);
        displayattpanel.setVisible(false);
        logoutpanel.setVisible(false);
        
        
        }catch(Exception e)
        {
            
        }
        
    }//GEN-LAST:event_addattbuttonActionPerformed

    private void brbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brbuttonActionPerformed
        // TODO add your handling code here:
        tdbbutton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(255, 255, 255)));
        addattbutton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(255, 255, 255)));
        brbutton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 6, 0, 0, new java.awt.Color(255, 255, 255)));
        
        tdashboardpanel.setVisible(false);
        addattpanel.setVisible(false);
        addatt2panel.setVisible(false);
        displayattpanel.setVisible(true);
        logoutpanel.setVisible(false);
        
        try
        {
            DefaultTableModel mt = (DefaultTableModel)logs_table.getModel();
            while(mt.getRowCount() > 0)
            {
            mt.removeRow(0);
            }
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/attendance?serverTimezone=UTC","root","");
            String sql=("Select class_code,subject_name,time,date,teacher_name From attendance_logs where teacher_name="+username);
            pat=conn.prepareStatement(sql);
            rs=pat.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)logs_table.getModel();
            while(rs.next()){
                Object o[]={rs.getString("class_code"),rs.getString("subject_name"),rs.getString("date"),rs.getString("time")};
                tm.addRow(o);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e); 
        }
        
    }//GEN-LAST:event_brbuttonActionPerformed

    private void addattlabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addattlabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addattlabel1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String class_box  = class_input.getSelectedItem().toString();
        String subject_box = subject_input.getSelectedItem().toString();
        String time_box = time_input.getSelectedItem().toString();
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        String date_box = df.format(date_input.getDate()).toString();
        
        int temp=0;
        TableModel model1 = display_table.getModel();
        String attendancex;
        int indexs[] = display_table.getSelectedRows();
        
        for(int i=0; i<model1.getRowCount(); i++)
        {
            if(display_table.isCellSelected(i, NORMAL))
            {
                //JOptionPane.showMessageDialog(this,model1.getValueAt(i,0).toString()+" is Present.");
                attendancex="Present";
                
            }
            else
            {
                //JOptionPane.showMessageDialog(this,"Row: "+ i +" not Selected.");
                //JOptionPane.showMessageDialog(this,model1.getValueAt(i,0).toString()+" is Absent.");
                attendancex="Absent";
            }
            
            try
            {
                
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/attendance?serverTimezone=UTC","root","");
            st=conn.createStatement();
            String sql=("Insert into attendance(roll_no,student_name,attendance,class_code,subject_id,time,date,teacher_name) Values('"+model1.getValueAt(i,0).toString()+"','"+model1.getValueAt(i,1).toString()+"','"+attendancex+"','"+class_box+"','"+subject_box+"','"+time_box+"','"+date_box+"','"+username+"')");
            st.executeUpdate(sql);
            temp++;
            }
            catch(Exception e)
            {
            System.out.println(e);
            }   
        }
        try{
        String sqll =("Insert into attendance_logs(class_code,subject_name,time,date,teacher_name) Values('"+class_box+"','"+subject_box+"','"+time_box+"','"+date_box+"','"+username+"')");
        st.executeUpdate(sqll);
        }catch(Exception e)
        {
            
        }
        if(temp!=0)
            {
                JOptionPane.showMessageDialog(this,"Attendance marked Successfully.");
                class_input.setSelectedIndex(-1);
                subject_input.setSelectedIndex(-1);
                time_input.setSelectedIndex(-1);
                date_input.setCalendar(null);
                jButton7.setVisible(true);
                
            DefaultTableModel mt = (DefaultTableModel)display_table.getModel();
            while(mt.getRowCount() > 0)
            {
            mt.removeRow(0);
            }
            }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try
        {
            
            //LocalDate localDate = LocalDate.of(, Month.January, 31);
            
            
            String cc = class_input.getSelectedItem().toString();
            //String sc = subject_input.getSelectedItem().toString();
            
            //jButton7.setVisible(false);
            
             DefaultTableModel mt = (DefaultTableModel)display_table.getModel();
            while(mt.getRowCount() > 0)
            {
            mt.removeRow(0);
            }
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/attendance?serverTimezone=UTC","root","");
            String sql=("Select enrollment_no,student_name From student where class_code='"+cc+"' order by enrollment_no");//
            pat=conn.prepareStatement(sql);
            rs=pat.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)display_table.getModel();
            while(rs.next()){
                  Object o[]={rs.getString("enrollment_no"),rs.getString("student_name")};
                 tm.addRow(o);
            }
            
            
        }catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void logs_tableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_logs_tableKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_logs_tableKeyPressed

    private void logs_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logs_tableMouseClicked
        // TODO add your handling code here:
        
          TableModel model1 = logs_table.getModel();
        

          int row = logs_table.getSelectedRow();
          
          String classs=model1.getValueAt(row,0).toString();
          String subjectx=model1.getValueAt(row,1).toString();
          String datex=model1.getValueAt(row,2).toString();
          String timex=model1.getValueAt(row,3).toString();
          
//          JOptionPane.showMessageDialog(this,row+" "+classs);
          
          String sql="Select roll_no,student_name,attendance From attendance where class_code='"+classs+"' AND subject_id='"+subjectx+"' AND date='"+datex+"' AND time='"+timex+"' AND teacher_name='"+username+"' order by roll_no";
          
          try
          {
            DefaultTableModel mt = (DefaultTableModel)attendance_table.getModel();
            while(mt.getRowCount() > 0)
            {
            mt.removeRow(0);
            }
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/attendance?serverTimezone=UTC","root","");
            pat=conn.prepareStatement(sql);
            rs=pat.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)attendance_table.getModel();
            while(rs.next())
            {
                  Object o[]={rs.getString("roll_no"),rs.getString("student_name"),rs.getString("attendance")};
                 tm.addRow(o);
            }
         }
          catch(Exception e)
          {
            JOptionPane.showMessageDialog(this,e);  
          }

    }//GEN-LAST:event_logs_tableMouseClicked

    private void select_input1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_input1ActionPerformed
        // TODO add your handling code here:
        display_table.selectAll();
    }//GEN-LAST:event_select_input1ActionPerformed

    private void display_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_display_tableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_display_tableMouseClicked

    private void logs_tableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logs_tableMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_logs_tableMouseExited

    private void logout_yes_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_yes_buttonActionPerformed
        // TODO add your handling code here:
        logoutpanel.setVisible(false);
        setVisible(false);
        this.dispose();
        Login lg=new Login();
        lg.setVisible(true);
    }//GEN-LAST:event_logout_yes_buttonActionPerformed

    private void logout_no_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_no_buttonActionPerformed
        // TODO add your handling code here:
        logoutpanel.setVisible(false);
        jPanel1.setVisible(true);
        addattpanel.setVisible(true);
        addatt2panel.setVisible(true);
        displayattpanel.setVisible(false);
    }//GEN-LAST:event_logout_no_buttonActionPerformed

    private void tdbbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdbbuttonActionPerformed
        tdbbutton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 6, 0, 0, new java.awt.Color(255, 255, 255)));
        addattbutton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(255, 255, 255)));
        brbutton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(255, 255, 255)));
        
        tdashboardpanel.setVisible(true);
        addattpanel.setVisible(false);
        addatt2panel.setVisible(false);
        displayattpanel.setVisible(false);
        logoutpanel.setVisible(false);
        
        
        Connection conn = databaseConnection.connection();
//            Statement stmt = conn.createStatement();
            Statement stmt=null;
            
            ResultSet rs;
         try
        {
            stmt = conn.createStatement();
         
            String sql = "SELECT count(subject_id) FROM attendance.subject_assign where teacher_id = '"+username+"'";                                                                                                 
            rs = stmt.executeQuery(sql);            
              
            if(rs.next()){
                 tNoOfSub.setText(rs.getString("count(subject_id)"));
             }  
            else{
               JOptionPane.showMessageDialog(null, "Record Not Found");
            }
        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
         
         
        try
        {
            stmt = conn.createStatement();
         
            String sql = "SELECT count(class_code) FROM attendance.subject_assign where teacher_id = '"+username+"'";                                                                                                 
            rs = stmt.executeQuery(sql);            
              
            if(rs.next()){
                 tNoOfclasses.setText(rs.getString("count(class_code)"));
             }  
            else{
               JOptionPane.showMessageDialog(null, "Record Not Found");
            }
        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        } 
        
                
        try
        {
//            Connection conn = databaseConnection.connection();
//            Statement stmt=null;
            stmt= conn.createStatement();
            
            String sql ="SELECT class_code,subject_name,subject_assign.subject_id,description FROM subject inner join subject_assign on subject_assign.subject_id = subject.subject_id where teacher_id ='"+username+"'";
            ResultSet res = stmt.executeQuery(sql);
            
            tdbdets.setModel(DbUtils.resultSetToTableModel(res));
        }catch(Exception e)
        { 
            JOptionPane.showMessageDialog(null,e); 
        }
       
    }//GEN-LAST:event_tdbbuttonActionPerformed

    private void dashboardlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardlabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardlabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogOut;
    private javax.swing.JPanel addatt2panel;
    private rojeru_san.RSButton addattbutton;
    private javax.swing.JLabel addattlabel;
    private javax.swing.JLabel addattlabel1;
    private javax.swing.JPanel addattpanel;
    private javax.swing.JPanel addsubject1;
    private javax.swing.JTable attendance_table;
    private rojeru_san.RSButton brbutton;
    private javax.swing.JComboBox<String> class_input;
    private javax.swing.JLabel dashboardlabel;
    private com.toedter.calendar.JDateChooser date_input;
    private javax.swing.JTable display_table;
    private javax.swing.JPanel displayattpanel;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel logout;
    private javax.swing.JButton logout_no_button;
    private javax.swing.JButton logout_yes_button;
    private javax.swing.JPanel logoutpanel;
    private javax.swing.JTable logs_table;
    private javax.swing.JButton select_input1;
    private javax.swing.JComboBox<String> subject_input;
    private javax.swing.JLabel tNoOfSub;
    private javax.swing.JLabel tNoOfclasses;
    private javax.swing.JPanel tdashboardpanel;
    private rojeru_san.RSButton tdbbutton;
    private rojerusan.RSTableMetro tdbdets;
    private javax.swing.JComboBox<String> time_input;
    private javax.swing.JLabel ttClasses;
    private javax.swing.JLabel ttSubs;
    private javax.swing.JLabel ttSubs1;
    // End of variables declaration//GEN-END:variables
}
